#############################################
## Default ansible catchall variables
#############################################

###############################
## SELinux
###############################
# selinux_policy can be "mls" or "targeted"
selinux_policy: "targeted"

# the state can be "enforcing","permissive", "disabled"
selinux_state: "enforcing"



###############################
## ntpclient
###############################

ntpclient_servers:
    - "192.168.0.254"


rhsm_subscribe_user: ""
rhsm_subscribe_password: ""

rhsm_repos_enabled_repos:
  - rhel-7-server-rpms

firewalld_ports:
    -   "443/tcp"
    -   "53/udp"

sshd_usedns: "no"
sshd_allow_root: "no"

#########################
# Satellite 6 bootstrap 
#########################

sat6_hostname: 'sat6.lab.local'
sat6_username: 'admin'
sat6_password: 'redhat'
sat6_org: 'lab'
sat6_location: 'laptop'
sat6_hostgroup: 'rhel7/Production'
sat6_activationkey: 'rhel7-prod'
bootstrap_force: yes

