---

  - template:
      src: sshd.conf.j2
      dest: /etc/ssh/sshd_config
      owner: root
      group: root
      mode: 0644
    become: yes
    notify: restart sshd
    tags:
      - sshd

  - name: enable SSHD
    service:
      name: sshd
      state: started
      enabled: yes
    become: yes
    notify: restart sshd
    tags:
      - sshd





